%Frequency demodulation
clc;
clear all;
close all;
t=[0: 0.001: 0.4];
fm =10;
v =cos(2*pi*fm*t);
subplot(4,1,1);
plot(t, v);
xlabel('Time');ylabel('Amplitude');
title('Message Signal');
fc=100;
c = sin(2*pi*fc*t);
subplot(4,1,2);
plot(t, c);
xlabel('Time');ylabel('Amplitude');
title('Carrier Signal');
m = 8;
f = sin((2*pi*fc*t)+(m.*sin(2*pi*fm*t)));
subplot(4,1,3);
plot(t, f);
xlabel('Time');ylabel('Amplitude');
title('Modulated Signal(FM)');
x = diff(f);
y = abs(x);
[b,a]=butter(4, 0.07);
de_mod = filter(b, a, y);
subplot(4,1,4);
plot(de_mod);
xlabel('Time');ylabel('Amplitude');
title('Demodulated signal');
